// Mock API layer. Replace each body with fetch('/api/...') later; UI code only calls API.*
const wait=(v,ms=500)=>new Promise(r=>setTimeout(()=>r(v),ms));
const API={
 getQuestions:({role})=>wait([`Tell me about yourself and why you want this ${role||'role'}.`,'Describe a difficult problem you solved and your approach.','How do you prioritise when everything is urgent?','Where do you see your skills growing in two years?'],400),
 evaluateAnswer:a=>{const s=Math.min(96,45+Math.round(a.length/7));return wait({score:s,communication:Math.min(95,s+4),technical:Math.max(40,s-6),confidence:Math.min(95,s),tips:['Open with a one-line summary before details.','Add one measurable result (%, time, revenue).','Use the STAR structure: Situation, Task, Action, Result.']},700)},
 getMockResult:o=>wait({overall:78,breakdown:{'Problem solving':82,Communication:75,'Role knowledge':80,'Time management':70,Confidence:74},summary:`${o.category} · ${o.role} · ${o.difficulty} · ${o.duration} min`},900),
 analyzeResume:()=>wait({score:72,found:['JavaScript','HTML','CSS','Git','REST APIs','Agile'],missing:['TypeScript','Unit testing','CI/CD','System design'],tips:['Add a skills section that mirrors the job description.','Quantify impact in each experience bullet.','Keep to one page and use a single-column layout.','Move projects above education for engineering roles.']},900),
 getProblems:()=>wait([{id:1,title:'Two Sum',level:'Easy',desc:'Given an array of integers and a target, return indices of the two numbers that add up to target.'},{id:2,title:'Valid Parentheses',level:'Easy',desc:'Determine if a string of brackets is valid and properly nested.'},{id:3,title:'Merge Intervals',level:'Medium',desc:'Merge all overlapping intervals and return the non-overlapping result.'},{id:4,title:'LRU Cache',level:'Medium',desc:'Design a cache that evicts the least recently used item in O(1).'},{id:5,title:'Median of Two Sorted Arrays',level:'Hard',desc:'Find the median of two sorted arrays in O(log(m+n)).'}],200),
 runCode:(code,submit)=>wait(code.trim().length<15?{ok:false,cases:[['Case 1','Fail'],['Case 2','Fail']]}:{ok:true,cases:[['Case 1','Pass'],['Case 2','Pass'],...(submit?[['Case 3','Pass'],['Edge case','Pass']]:[])],runtime:'48 ms'},600),
 getFeedback:()=>wait({communication:82,technical:76,confidence:70,strengths:['Clear, structured answers','Strong fundamentals in JavaScript','Good use of examples'],weaknesses:['Answers run long under pressure','Few quantified outcomes'],suggestions:['Practise 90-second answers','Record yourself and review pace','Prepare 3 metric-backed stories'],recent:[{t:'Frontend Developer',d:'Sep 28',s:84,n:'Strong technical depth; tighten the closing.'},{t:'Behavioral Round',d:'Sep 25',s:76,n:'Good stories; add measurable results.'},{t:'System Design',d:'Sep 21',s:68,n:'Clarify requirements before designing.'}]}),
 getPerformance:()=>wait({overall:79,stats:[['Interviews','24'],['Hours practised','18.5'],['Problems solved','47'],['Streak','6 days']],trend:[58,62,61,68,72,75,79],history:[['Sep 28','Frontend Developer','Technical',84],['Sep 25','Behavioral','HR',76],['Sep 21','System Design','Technical',68],['Sep 18','Backend Developer','Mock',80]],skills:{Communication:82,'Problem solving':78,'Technical depth':76,Confidence:70,'Time management':65},activity:['Completed Frontend Developer mock interview','Solved "Merge Intervals"','Resume ATS score improved to 72','Reviewed feedback for Behavioral Round']},300)};
// ---- Extended mock data (replace with fetch() later) ----
const BANK={Technical:['Explain the difference between var, let and const.','How does the browser render a page, from URL to pixels?','What is event delegation and why is it useful?','How would you debug a memory leak in a web app?','Compare REST and GraphQL: when would you choose each?'],
Behavioral:['Tell me about a time you disagreed with a teammate.','Describe a project you are proud of and your role in it.','Tell me about a failure and what you learned.','How do you handle tight deadlines?','Describe a time you received difficult feedback.'],
'System Design':['Design a URL shortener.','Design a notification system for millions of users.','How would you design a rate limiter?','Design a simple chat application.','How would you scale a read-heavy API?'],
HR:['Why do you want to join our company?','Where do you see yourself in five years?','What are your salary expectations?','Why are you leaving your current role?','What are your strengths and weaknesses?']};
Object.assign(API,{
 getQuestions:({category,type})=>wait([...(BANK[category||type]||BANK.Technical)],400),
 getMockResult:(o,qs=[],ans=[])=>{const items=qs.map((q,i)=>{const a=ans[i]||'';const s=a?Math.min(95,40+Math.round(a.length/6)):0;return{q,a,score:s,tip:!a?'Skipped: attempt every question, even briefly.':s<65?'Add a concrete example and a measurable result.':'Solid. Tighten the opening and close with the outcome.'}});
  const answered=items.filter(x=>x.a),ov=answered.length?Math.round(items.reduce((t,x)=>t+x.score,0)/items.length):0,c=(d)=>Math.max(0,Math.min(98,ov+d));
  return wait({overall:ov,items,summary:`${o.category} · ${o.role} · ${o.difficulty} · ${o.duration} min`,breakdown:{'Problem solving':c(4),Communication:c(-2),'Role knowledge':c(2),'Time management':c(-6),Confidence:c(-3)}},900)},
 getProblems:()=>wait([
  {id:1,title:'Two Sum',level:'Easy',acc:'51.2%',status:'solved',topics:['Array','Hash Table'],desc:'Given an array of integers and a target, return the indices of the two numbers that add up to target.',ex:'Input:  nums = [2,7,11,15], target = 9\nOutput: [0,1]'},
  {id:2,title:'Valid Parentheses',level:'Easy',acc:'40.8%',status:'solved',topics:['String','Stack'],desc:'Determine whether a string of brackets is valid and correctly nested.',ex:'Input:  s = "()[]{}"\nOutput: true'},
  {id:3,title:'Reverse Linked List',level:'Easy',acc:'74.6%',status:'attempted',topics:['Linked List'],desc:'Reverse a singly linked list and return the new head.',ex:'Input:  1->2->3->4\nOutput: 4->3->2->1'},
  {id:4,title:'Merge Intervals',level:'Medium',acc:'46.1%',status:'attempted',topics:['Array','Sorting'],desc:'Merge all overlapping intervals and return the non-overlapping result.',ex:'Input:  [[1,3],[2,6],[8,10]]\nOutput: [[1,6],[8,10]]'},
  {id:5,title:'LRU Cache',level:'Medium',acc:'41.0%',status:'todo',topics:['Design','Hash Table'],desc:'Design a cache that evicts the least recently used item with O(1) get and put.',ex:'put(1,1) put(2,2) get(1) -> 1'},
  {id:6,title:'Number of Islands',level:'Medium',acc:'60.3%',status:'todo',topics:['Graph','DFS'],desc:'Count the islands in a 2D grid of land and water.',ex:'Input:  11000/11000/00100/00011\nOutput: 3'},
  {id:7,title:'Median of Two Sorted Arrays',level:'Hard',acc:'43.5%',status:'todo',topics:['Binary Search'],desc:'Find the median of two sorted arrays in O(log(m+n)).',ex:'Input:  [1,3], [2]\nOutput: 2.0'}],200),
 getHeatmap:()=>{let s=7;return wait(Array.from({length:182},()=>{s=(s*9301+49297)%233280;const r=s/233280;return r<.35?0:r<.6?1:r<.8?2:r<.93?3:4}),200)},
 getDashboard:()=>wait({user:{name:'Alex Morgan',initials:'AM',headline:'Aspiring Frontend Developer',stats:[['Interviews','24'],['Streak','6 days'],['Problems','47']]},
  daily:{title:'Merge Intervals',level:'Medium',topics:['Array','Sorting']},
  feed:[{n:'Priya Nair',i:'PN',t:'2h',x:'Completed a System Design mock interview and scored 81/100.',m:['System Design','81/100'],l:24,c:3},{n:'Daniel Kim',i:'DK',t:'5h',x:'Solved "Merge Intervals" in 18 minutes.',m:['Coding','Medium'],l:41,c:7},{n:'Sara Ali',i:'SA',t:'1d',x:'Raised my ATS score from 58 to 76 after adding missing keywords.',m:['Resume/ATS','76/100'],l:58,c:11},{n:'You',i:'AM',t:'2d',x:'6-day practice streak. Keep going!',m:['Streak','6 days'],l:12,c:1}],
  board:[['Priya Nair',92],['Daniel Kim',88],['Alex Morgan',79],['Sara Ali',76],['Leo Martin',71]],
  stories:[['AI','ai-interview','Interview',0],['MI','mock-interviews','Mock',0],['CV','resume-ats','Resume',1],['</>','coding','Coding',0],['FB','feedback','Feedback',1],['PT','performance','Progress',1]]},300)});
