const sb=$('#submitAnswer'),an=$('#answer'),fb=$('#feedback'),st=$('#status');
sb?.addEventListener('click',async()=>{if(an.value.trim().length<12){an.focus();st.textContent='Write a little more before submitting.';st.className='err';return}
sb.disabled=true;sb.textContent='Analysing…';st.textContent='';const r=await API.evaluateAnswer(an.value);
fb.innerHTML=`<div class="fb-head"><h3>Sample evaluation</h3><span class="score">${r.score}<small>/100</small></span></div>${bar('Communication',r.communication)}${bar('Technical',r.technical)}${bar('Confidence',r.confidence)}<p class="note">Generated by mock scoring logic, not a real AI model.</p>`;
fb.hidden=false;sb.disabled=false;sb.textContent='Submit again'});
